export const hybridLectureRagConfig = {
  minScoreThreshold: 0.2,
  lectureTopK: 4,
  courseTopK: 4,
  finalTopK: 3,
  maxAnswerSentences: 3,
  chunkSizeWords: 90,
  chunkOverlapWords: 18,
  denseWeight: 0.55,
  sparseWeight: 0.45,
  lexicalWeight: 0.35,
  metadataWeight: 0.15,
  lectureScopeBoost: 1.35,
  courseScopeBoost: 0.9,
  repeatedSourcePenalty: 0.12,
  genericSectionPenalty: 0.28,
  sentenceRelevanceThreshold: 0.3,
  chunkLexicalFloor: 0.12,
  chunkMetadataFloor: 0.18,
  strongIntentSentenceBoost: 0.55,
  sourceTypeBoosts: {
    transcript: 1.04,
    notes: 1.08,
    slides: 1,
    reading: 0.96,
  },
} as const
