import type { FacultySourceDocument } from '@/lib/rag/types'

export const facultySourceDocuments: FacultySourceDocument[] = [
  {
    id: 'cs301-l08-notes-balanced-vs-complete',
    institutionId: 'onestop-demo',
    facultyId: 'faculty-nk',
    courseId: 'cs-301',
    courseName: 'Data Structures & Algorithms',
    lectureId: 'cs-301-lecture-08',
    lectureTitle: 'Trees, Graphs & Traversals',
    lectureSequence: 8,
    topic: 'Binary search trees',
    sourceType: 'notes',
    sourceName: 'Lecture 08 Notes',
    section: 'Balanced vs complete trees',
    page: 4,
    updatedAt: '2026-08-13T09:00:00.000Z',
    content:
      'A complete tree is filled level by level from left to right without gaps before a new level begins. A balanced tree focuses on keeping subtree heights close so operations remain efficient. A tree can be complete without being height-balanced, and balanced without being complete.',
  },
  {
    id: 'cs301-l08-transcript-insertion-shape',
    institutionId: 'onestop-demo',
    facultyId: 'faculty-nk',
    courseId: 'cs-301',
    courseName: 'Data Structures & Algorithms',
    lectureId: 'cs-301-lecture-08',
    lectureTitle: 'Trees, Graphs & Traversals',
    lectureSequence: 8,
    topic: 'Binary search trees',
    sourceType: 'transcript',
    sourceName: 'Lecture 08 Transcript',
    section: 'Insertion reasoning',
    timestamp: '42:18',
    updatedAt: '2026-08-13T09:05:00.000Z',
    content:
      'During insertion, completeness is about where the next node is allowed to appear in level order, while balance is about whether repeated insertions make one side much deeper than the other. Balance protects lookup and update cost by limiting height growth.',
  },
  {
    id: 'cs301-l08-slides-traversals',
    institutionId: 'onestop-demo',
    facultyId: 'faculty-nk',
    courseId: 'cs-301',
    courseName: 'Data Structures & Algorithms',
    lectureId: 'cs-301-lecture-08',
    lectureTitle: 'Trees, Graphs & Traversals',
    lectureSequence: 8,
    topic: 'Traversals',
    sourceType: 'slides',
    sourceName: 'Lecture 08 Slides',
    section: 'Traversal recap',
    page: 11,
    updatedAt: '2026-08-13T09:10:00.000Z',
    content:
      'Preorder visits root before subtrees, inorder visits left subtree then root then right subtree, and postorder visits root last. In binary search trees, inorder traversal yields values in sorted order.',
  },
  {
    id: 'cs301-l08-notes-practice',
    institutionId: 'onestop-demo',
    facultyId: 'faculty-nk',
    courseId: 'cs-301',
    courseName: 'Data Structures & Algorithms',
    lectureId: 'cs-301-lecture-08',
    lectureTitle: 'Trees, Graphs & Traversals',
    lectureSequence: 8,
    topic: 'Exam preparation',
    sourceType: 'notes',
    sourceName: 'Lecture 08 Notes',
    section: 'What to review',
    page: 6,
    updatedAt: '2026-08-13T09:12:00.000Z',
    content:
      'For exam preparation, review the definition of height, the difference between complete and balanced trees, and why inorder traversal is useful for binary search trees. Practice tracing insertions that make a tree skewed.',
  },
  {
    id: 'cs301-l07-notes-tree-height',
    institutionId: 'onestop-demo',
    facultyId: 'faculty-nk',
    courseId: 'cs-301',
    courseName: 'Data Structures & Algorithms',
    lectureId: 'cs-301-lecture-07',
    lectureTitle: 'Tree Foundations',
    lectureSequence: 7,
    topic: 'Height and depth',
    sourceType: 'notes',
    sourceName: 'Lecture 07 Notes',
    section: 'Height basics',
    page: 2,
    updatedAt: '2026-08-12T09:00:00.000Z',
    content:
      'Tree height measures the longest path from the root to a leaf. If the tree becomes skewed, operations that depend on path length degrade toward linear time.',
  },
  {
    id: 'cs301-course-reading-avl',
    institutionId: 'onestop-demo',
    facultyId: 'faculty-nk',
    courseId: 'cs-301',
    courseName: 'Data Structures & Algorithms',
    lectureId: 'cs-301-course-resource',
    lectureTitle: 'Course Resources',
    lectureSequence: 0,
    topic: 'AVL trees',
    sourceType: 'reading',
    sourceName: 'AVL Tree Reference',
    section: 'Why balance matters',
    page: 1,
    updatedAt: '2026-08-11T09:00:00.000Z',
    content:
      'Self-balancing trees such as AVL trees maintain structural constraints so search, insertion, and deletion remain logarithmic in the number of stored elements.',
  },
]
